import{a as E,S as w,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const P=E.create({baseURL:"https://pixabay.com/api/",params:{key:"53362623-c21c250e54a945e6b56a0ca7f",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});async function f(o,a){try{return(await P.get("",{params:{q:o,page:a}})).data}catch(s){throw s}}const r={galleryEl:document.querySelector(".gallery"),loaderEl:document.querySelector(".loader"),btnLoadEl:document.querySelector(".btn-load-more"),formEl:document.querySelector(".form")},S=new w(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",captions:!0});function h(o){const a=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:n,comments:b,downloads:L})=>`<li class="gallery-item">
    <a class="gallery-link" href="${i}">
    <img class="gallery-image" src="${s}" alt="${e}" />
    </a>
    <dl class="gallery-stats-list">
        <dt class="title">Likes</dt><dd class="numbers">${t}</dd>
        <dt class="title">Views</dt><dd class="numbers">${n}</dd>
        <dt class="title">Comments</dt><dd class="numbers">${b}</dd>
        <dt class="title">Downloads</dt><dd class="numbers">${L}</dd>
    </dl>
        </li>`).join("");r.galleryEl.insertAdjacentHTML("beforeend",a),S.refresh()}function q(){r.galleryEl.innerHTML=""}function y(){r.loaderEl.classList.remove("hidden"),r.loaderEl.setAttribute("aria-busy","true")}function p(){r.loaderEl.classList.add("hidden"),r.loaderEl.setAttribute("aria-busy","false")}function u(){r.btnLoadEl.classList.remove("hidden")}function g(){r.btnLoadEl.classList.add("hidden")}let c,d,m;r.formEl.addEventListener("submit",async o=>{if(o.preventDefault(),d=(new FormData(o.currentTarget).get("search-text")||"").trim(),!d){l.warning({message:"Please enter a search query",position:"topRight"});return}y(),q(),g(),c=1;try{const{hits:s,totalHits:i}=await f(d,c);if(m=Math.ceil(i/15),!s.length){l.info({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",progressBarColor:"#b51b1b"});return}h(s),m>1?u():g()}catch{l.error({message:"Something went wrong.",position:"topRight"})}finally{p(),r.formEl.reset()}});r.btnLoadEl.addEventListener("click",async()=>{c+=1,g(),y();try{const{hits:o}=await f(d,c);h(o);const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"}),c<m?u():l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040",progressBarColor:"#b51b1b"})}catch{l.error({message:"Something went wrong.",position:"topRight"}),u()}finally{p()}});
//# sourceMappingURL=index.js.map
