import{a as m,S as f,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const g=m.create({baseURL:"https://pixabay.com/api/",params:{key:void 0,image_type:"photo",orientation:"horizontal",safesearch:!0}});function p(s){return g.get("",{params:{q:s}}).then(r=>r.data.hits).catch(r=>{throw r})}const c=document.querySelector(".gallery"),n=document.querySelector(".loader"),h=new f(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",captions:!0});function y(s){const r=s.map(({webformatURL:a,largeImageURL:o,tags:e,likes:t,views:i,comments:d,downloads:u})=>`<li class="gallery-item">
    <a class="gallery-link" href="${o}">
    <img class="gallery-image" src="${a}" alt="${e}" />
    </a>
    <dl class="gallery-stats-list">
        <dt class="title">Likes</dt><dd class="numbers">${t}</dd>
        <dt class="title">Views</dt><dd class="numbers">${i}</dd>
        <dt class="title">Comments</dt><dd class="numbers">${d}</dd>
        <dt class="title">Downloads</dt><dd class="numbers">${u}</dd>
    </dl>
        </li>`).join("");c.insertAdjacentHTML("beforeend",r),h.refresh()}function b(){c.innerHTML=""}function L(){n.classList.remove("hidden"),n.setAttribute("aria-busy","true")}function w(){n.classList.add("hidden"),n.setAttribute("aria-busy","false")}const q=document.querySelector(".form");q.addEventListener("submit",s=>{s.preventDefault();const a=(new FormData(s.currentTarget).get("search-text")||"").trim();if(!a){l.warning({message:"Please enter a search query",position:"topRight"});return}L(),b(),p(a).then(o=>{if(!o.length){l.info({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",progressBarColor:"#b51b1b"});return}y(o)}).catch(()=>{l.error({message:"Something went wrong.",position:"topRight"})}).finally(()=>{w()}),s.currentTarget.reset()});
//# sourceMappingURL=index.js.map
